# Site settings
title: NONSENSE
description: "A heterogeneous mixture of hobbyist electronics revelations, rudimentary coding hacks and thought provoking hypotheses on 42."
baseurl: ""
url: "http://prabhpreet.github.io"
facebook_username: prabhpreet.dua
github_username:  prabhpreet

# Build settings
markdown: kramdown
permalink: pretty
